name: Clear Cache
on:

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
     - name: multiple command
       uses: appleboy/ssh-action@master
       with:
         host: ${{ secrets.FTP_SERVER }}
         username: ${{ secrets.FTP_USERNAME }}
         key: ${{secrets.SSH_KEY}}
         port: ${{ secrets.PORT }}
         script: |
           cd /home/amackapp.com/public_html/api/
           ls
           php artisan config:clear
           php artisan cache:clear
           php artisan config:cache
           php artisan passport:install
