name: Clear Cache
on:

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
     - name: multiple command
       uses: Samkirkland/FTP-Deploy-Action@3.1.1
       with:
        ftp-server: ${{ secrets.FTP_SERVER }}
        ftp-username: ${{ secrets.FTP_USERNAME }}
        ftp-password: ${{secrets.FTP_PASSWORD}}
        script: |
           cd /home/amackapp/public_html/api/api/
           ls
           git pull origin dev
           php artisan config:clear
           php artisan cache:clear
           php artisan config:cache
           php artisan passport:install
           
